version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: qurl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/qurl
    binary: qurl
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    formats:
      - tar.gz
      - zip
    format_overrides:
      - goos: windows
        formats:
          - zip
      - goos: linux
        formats:
          - tar.gz
      - goos: darwin
        formats:
          - tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  github:
    owner: bkeane
    name: qurl
  prerelease: auto
  draft: false
  name_template: "{{ .Tag }}"
  footer: |
    ---

    ## Installation

    ### Quick install (coming soon)
    ```bash
    # Mac/Linux
    curl -sS https://webi.sh/qurl | sh

    # Windows
    curl.exe -A MS https://webi.ms/qurl | powershell
    ```

    ### Manual install
    Download the appropriate archive below and extract the binary to your PATH.

    ---

    **Full Changelog**: https://github.com/bkeane/qurl/compare/{{ .PreviousTag }}...{{ .Tag }}